

CREATE TABLE DOCUMENTOS_IDENTIDAD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL
);

CREATE TABLE COLABORADORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DOCUMENTO INT NOT NULL,
    N_DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    APELLIDOS_NOMBRES VARCHAR(255) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    AREA VARCHAR(100),
    CORREO VARCHAR(100),
    APROBADOR_1 VARCHAR(100),
    APROBADOR_2 VARCHAR(100),
    FOREIGN KEY (TIPO_DOCUMENTO) REFERENCES DOCUMENTOS_IDENTIDAD(ID)
);

CREATE TABLE DOCUMENTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE LEGAJO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DOCUMENTO INT NOT NULL,
    N_DOCUMENTO VARCHAR(20) NOT NULL,
    DOCUMENTO_ID INT NOT NULL,
    EJERCICIO YEAR NOT NULL,
    PERIODO CHAR(2) NOT NULL,
    EMITIDO TEXT,
    EMITIDO_USUARIO INT,
    EMITIDO_HORA DATETIME,
    EMITIDO_OBSERVACION TEXT,
    SUBIDO TEXT,
    SUBIDO_USUARIO INT,
    SUBIDO_HORA DATETIME,
    SUBIDO_OBSERVACION TEXT,
    FISICO BOOLEAN,
    FISICO_USUARIO INT,
    FISICO_HORA DATETIME,
    FISICO_OBSERVACION TEXT,
    FOREIGN KEY (TIPO_DOCUMENTO) REFERENCES DOCUMENTOS_IDENTIDAD(ID),
    FOREIGN KEY (DOCUMENTO_ID) REFERENCES DOCUMENTOS(ID)
);

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL ENUM('NOMINAS', 'RRHH', 'RECEPCION', 'ADMIN') NOT NULL
);
